services:
  backend:
    build:
      context: backend
    command: "cargo watch -x run --poll"
    volumes:
      - ./backend:/projects
    working_dir: /projects
    environment:
      - USER=user
    ports:
      - "8080:8080"
